apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: kcp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kcp
    app.kubernetes.io/part-of: kcp
  name: kcp
  namespace: ralphjbean
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: kcp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: kcp
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:ralphjbean-kcp
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
